#!/usr/bin/env bash
#
# Rebuild the prebuilt whd_gen binaries that ship with a release.
#
# The release runner (a Raspberry Pi 5) does NOT compile whd_gen: it only copies
# prebuilt/whd_gen/* into releases/. So these binaries are built here, by hand,
# and committed. Run this after changing anything whd_gen compiles -- the sources
# listed in WHD_GEN_SOURCES below -- then commit prebuilt/whd_gen/ before tagging.
# buildAll.sh warns when the committed binaries are older than those sources.
#
# Usage:
#   ./update-prebuilt-whd_gen.sh                 # all three release targets
#   ./update-prebuilt-whd_gen.sh linux-x64       # just one
#
# Toolchains needed (x86_64 Linux host):
#   linux-x64     g++                      (usually already installed)
#   win64         g++-mingw-w64-x86-64     sudo apt install g++-mingw-w64-x86-64
#   linux-arm64   a standalone aarch64 GCC -- see the note below
#
# For linux-arm64, do NOT `apt install g++-aarch64-linux-gnu`: on Ubuntu 24.04
# that package Breaks/Replaces gcc-multilib and g++-multilib, so apt removes
# them, and any -m32 build on the machine stops working (this bit the 32-bit
# InfoNES build). Use a standalone toolchain tarball instead, e.g. the ARM GNU
# Toolchain aarch64-none-linux-gnu build, and point this script at it:
#
#   CC_ARM64=/opt/arm-gnu/bin/aarch64-none-linux-gnu-gcc \
#   CXX_ARM64=/opt/arm-gnu/bin/aarch64-none-linux-gnu-g++ \
#     ./update-prebuilt-whd_gen.sh
#
# 32-bit Windows is intentionally not published. `src/whd_gen/build_native.sh
# win32` still builds it for anyone who asks.
#
set -euo pipefail

cd "$(dirname "$0")"

OUT_DIR=prebuilt/whd_gen
BUILDER=src/whd_gen/build_native.sh

# Everything whd_gen compiles; used for the staleness stamp in VERSIONS.txt.
WHD_GEN_SOURCES=(src/whd_gen src/tiny_huff.c src/musx_decoder.c src/image_decoder.c src/adpcm-xq)

ALL_TARGETS=(linux-x64 linux-arm64 win64)
if [ $# -gt 0 ]; then
    targets=("$@")
else
    targets=("${ALL_TARGETS[@]}")
fi

mkdir -p "$OUT_DIR"
for target in "${targets[@]}"; do
    case "$target" in
        linux-x64)    artifact=whd_gen-linux-x64;   cc=""; cxx="" ;;
        linux-arm64)  artifact=whd_gen-linux-arm64
                      cc="${CC_ARM64:-}"; cxx="${CXX_ARM64:-}" ;;
        win64)        artifact=whd_gen-win64.exe;   cc=""; cxx="" ;;
        *)
            echo "unknown target '$target' (expected one of: ${ALL_TARGETS[*]})" >&2
            exit 1 ;;
    esac

    echo
    echo "=== $target -> $OUT_DIR/$artifact ==="
    # Per-target compiler overrides are passed through to build_native.sh, which
    # already honours CC/CXX; this keeps a tarball toolchain out of PATH.
    if [ -n "$cxx" ]; then
        CC="$cc" CXX="$cxx" "$BUILDER" "$target"
    else
        "$BUILDER" "$target"
    fi
    mv "src/whd_gen/$artifact" "$OUT_DIR/$artifact"
    chmod +x "$OUT_DIR/$artifact"
done

# --- provenance -------------------------------------------------------------
# Records the commit the sources were at, so buildAll.sh can tell whether the
# committed binaries have fallen behind. The table is rebuilt from whatever is
# currently in $OUT_DIR rather than from the targets built in this run, so a
# single-target run does not silently drop the other entries.
stamp_commit=$(git rev-list -1 HEAD -- "${WHD_GEN_SOURCES[@]}" 2>/dev/null || echo unknown)
stamp_date=$(git log -1 --format=%cI "$stamp_commit" 2>/dev/null || echo unknown)
versions="$OUT_DIR/VERSIONS.txt"

{
    echo "# whd_gen prebuilt binaries -- generated by update-prebuilt-whd_gen.sh"
    echo "# 'source-commit' is the last commit touching what whd_gen compiles;"
    echo "# buildAll.sh compares it against HEAD to detect stale binaries."
    echo "source-commit: $stamp_commit"
    echo "source-date:   $stamp_date"
    echo
    for path in "$OUT_DIR"/whd_gen-*; do
        [ -f "$path" ] || continue
        artifact=$(basename "$path")
        size=$(stat -c%s "$path")
        printf '%-24s %8s bytes  %s\n' "$artifact" "$size" \
            "$(file -b "$path" | cut -d, -f1-2)"
    done
} > "$versions"

if [ "${#targets[@]}" -lt "${#ALL_TARGETS[@]}" ]; then
    echo
    echo "NOTE: partial run (${targets[*]}). VERSIONS.txt now stamps ALL binaries in" >&2
    echo "      $OUT_DIR with HEAD's source commit -- rerun without arguments before" >&2
    echo "      tagging so every binary really is built from these sources." >&2
fi

echo
echo "=== $versions ==="
cat "$versions"
echo
echo "=== file(1) -- check each architecture is what it claims ==="
file "$OUT_DIR"/whd_gen-*
echo
echo "Now commit $OUT_DIR/ before tagging a release."
